# fly.toml app configuration file for zima-auto-frontend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'zima-auto-frontend'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  VITE_BACKEND_API_URL = "https://zima-auto-backend.fly.dev"
  VITE_GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycby1xiEPUaIJdhJd7h6v6Gzr7xL80fk-li9bJKOwv0-ZcrQ_1vzqJXW4ghnYy8LPMpXo/exec"  # Sheets Script URL
  VITE_GOOGLE_DOCS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbzs6b-VCT2Zge6aVd2tc8aGvh2cqPRtl8GI4yXI-fhmHQgtxQs8IOVdEpLJ6hcvz2MnPg/exec"  # Docs Script URL

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
